Programs completed in codewars
ibratnawaz/DEP-training pull request #3
Opened 2021-12-09 11:55 UTC by ibratnawaz

Yesterday's and today's programming task completed in codewars.

@suraj-pareek  Please review it and provide the feedback. Thanks

2021-12-22 06:06 UTC, suraj-pareek requested changes

2021-12-22 06:06 UTC, suraj-pareek commented on calculation.js
> +      case '/': ans = value1 / value2;
Please also add a default case where you can throw errors like Invalid operations.

2021-12-22 06:06 UTC, suraj-pareek commented on discount.js
> +    if(d >= 7) disc = 50;
Please avoid using magic numbers;

2021-12-22 06:06 UTC, suraj-pareek commented on middleCharacter.js
> +  if(s.length%2==0) return s[s.length/2 - 1]+s[s.length/2]
rename function name to getMiddleChar or extractMiddleChar.

Also, define if block to improve the readability and use semi-colon; Although not required, it's good to use.

2021-12-22 06:06 UTC, suraj-pareek commented on oppositeNumber.js
> +    return number > 0 ? -number : number == 0 ? 0 : -number;
here also, the function name should be oppositeNumber() according to me, otherwise what if we pass string value what would be the case here.

2021-12-22 06:06 UTC, suraj-pareek commented on partition.js
> +    const obj={}
please write full code first.

2021-12-22 06:06 UTC, suraj-pareek commented on arrayHelpers.js
> +  if (!this.length) return NaN;
Do we really need this check as the average function is associated with Array([]) which already has a length property?

2021-12-22 06:06 UTC, suraj-pareek commented on calculation.js
> +function basicOp(operation, value1, value2) {
please provide the clear function/variables names;

2021-12-22 06:06 UTC, suraj-pareek commented on classState.js
> +var Cat = (function () {
Can you please explain why did you use IIFE here?

2021-12-22 06:06 UTC, suraj-pareek commented on closuresScopes.js
> +function createFunctions(length) {
I would recommend avoiding the use of var anymore 
FYI please read https://hackernoon.com/why-you-shouldnt-use-var-anymore-f109a58b9b70

2021-12-22 06:06 UTC, suraj-pareek commented on discount.js
> +  let totalCost = 40 * days;
please avoid uses of magic numbers;

2021-12-22 06:06 UTC, suraj-pareek commented on fillArray.js
> +  try {
This function shouldn't catch the error it just throws the error.
Can you please optimize the code as well? Just see how can remove a few checks.

2021-12-22 06:06 UTC, suraj-pareek commented on functionComposition-2.js
> +    for (let i = args.length - 1; i >= 0; i--) {
please don't use variable names like i or j.

2021-12-22 06:06 UTC, suraj-pareek commented on middleCharacter.js
> +  if (string.length % 2 == 0)
rename the param name to value instead of string;

2021-12-22 06:06 UTC, suraj-pareek commented on nestedObjectReference.js
> +Object.prototype.hash = function (string) {
rename the variable name  "string" to "value", "obj" to "data" and "i" to "index"  ( which make more sense here);
Also, this program will throw an error if we call it data.hash(), so please handle this as well;

2021-12-22 06:06 UTC, suraj-pareek commented on oppositeNumber.js
> +function opposite(number) {
I think here function name should be oppositeNumber() or getOppositeNumber();

2021-12-22 06:06 UTC, suraj-pareek commented on partition.js
> +  const arrE = [];
please define the variable's name properly denoting the values it holds like below -
arrE ---> evenElements / evenNumbers;
arrO --> oddElements / oddNumbers;

2021-12-23 08:30 UTC, ibratnawaz commented
@suraj-pareek, Please review it. Thank you.

2021-12-23 08:31 UTC, ibratnawaz commented on nestedObjectReference.js
> +Object.prototype.hash = function (string) {
In the question it's written a path will always be passed to this hash() function.

2021-12-28 07:30 UTC, suraj-pareek requested changes

2021-12-28 07:30 UTC, suraj-pareek commented on discount.js
> +  if (days >= 7) discount = 50;
please avoid using magic numbers;

2021-12-28 07:30 UTC, suraj-pareek commented on functionComposition-2.js
> +const addOne = (value) => value + 1;
please avoid using magic numbers;

2021-12-28 07:30 UTC, suraj-pareek commented on middleCharacter.js
> +    return value[value.length / 2 - 1] + value[value.length / 2];
please avoid using magic numbers also hold the middle value in a meaningful defined variable.

2021-12-28 07:30 UTC, suraj-pareek commented on partition.js
> +  return value % 2 == 0;
it's good to use strict type equal operator

2022-01-04 12:24 UTC, ibratnawaz commented
@suraj-pareek, Please review this too. Thank you.

2022-01-07 07:13 UTC, suraj-pareek requested changes

2022-01-07 07:13 UTC, suraj-pareek commented on partition.js
> +    else oddElements.push(item);
please use if-else brackets;

2022-01-07 07:13 UTC, suraj-pareek commented on middleCharacter.js
> +    return value[middlePosition - numbers.ONE] + value[middlePosition];
please use if blocks;

2022-01-07 07:13 UTC, suraj-pareek commented on functionComposition-2.js
> +      let index = args.length - numbers.ONE;
can we have index values assignment before for block?

2022-01-07 07:13 UTC, suraj-pareek commented on discount.js
> +  else if (days >= daysCount.MIN) discount = discountCharges.MIN;
please add if-else block

2022-01-11 09:27 UTC, ibratnawaz commented
@suraj-pareek, Please review it. Thanks

2022-01-19 12:37 UTC, suraj-pareek approved these changes
Good Job!

2022-01-19 12:39 UTC, closed without merging