Node Task - Creating CRUD APIs using express
ibratnawaz/DEP-training pull request #7
Opened 2022-01-23 07:07 UTC by ibratnawaz

- Using express creating CRUD APIs for the users.
- Storing the data in PostgreSQL.

2022-01-23 12:34 UTC, ibratnawaz commented
@suraj-pareek, please review it. Thank you

2022-01-28 12:50 UTC, suraj-pareek requested changes
Good work!

2022-01-28 12:50 UTC, suraj-pareek commented on src/middlewares/authenticate.ts
> +      res.status(400).json({ error: "Email is already taken." });
It's a good practice to keep all HTTP status codes in a separate config/constant module.

2022-01-28 12:50 UTC, suraj-pareek commented on src/models/user.ts
> +          msg: "Fist name cannot be empty.",
please correct the typo error.

2022-01-28 12:50 UTC, suraj-pareek commented on src/middlewares/validate.ts
> +  const keys = ["firstName", "lastName", "login", "password", "age"];
please make it generic to handle all collections.

2022-01-28 12:50 UTC, suraj-pareek commented on src/routes/userRoutes.ts
> +  .post([payloadValidation, checkDuplicateEmail], createUser)
please give the appropriate middleware and controller name.

2022-01-29 07:15 UTC, ibratnawaz commented
@suraj-pareek Please review it. Thank you

2022-02-02 03:49 UTC, suraj-pareek requested changes

2022-02-02 03:49 UTC, suraj-pareek commented on src/routes/userRoutes.ts
> +router.get("/soft-deletes/list", getSoftDeltedUsers);
please correct endpoint;

2022-02-02 03:49 UTC, suraj-pareek commented on src/models/user.ts
> +        isAlpha: { msg: "Please prove valid first name." },
please change the message as per fields

2022-02-02 03:49 UTC, suraj-pareek commented on src/middlewares/validate.ts
> +export const validation = (User: { rawAttributes: {} }) => {
Please rename it to user validation as still its not generic validation. If you want to make it generic validation then you would get the columns/fields from the given schema and iterate over its properties.

2022-02-02 03:49 UTC, suraj-pareek commented on src/routes/userRoutes.ts
> +  getSoftDeltedUsers,
can we have actives/inactive users instead of soft delete?

2022-02-02 08:07 UTC, ibratnawaz commented
@suraj-pareek Please review it. Thank you

2022-02-09 09:26 UTC, ibratnawaz commented
Hi Suraj,
I have renamed the end-points and functions name as per you suggestion

2022-02-15 04:51 UTC, suraj-pareek approved these changes
Good Work!

2022-02-15 07:58 UTC, closed without merging